<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Poemas del Cliente</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background-color: #f9fafd;
            font-family: 'Arial', sans-serif;
        }

        #menu {
            background-color: #313a46;
            color: #ffffff;
            box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.1);
        }

        .navbar-brand {
            font-weight: bold;
            font-size: 1.5rem;
        }

        #poemas {
            padding: 20px;
            text-align: center;
            margin-top: 20px;
            border-radius: 8px;
            background-color: #ffffff;
            box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);
        }
    </style>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark" id="menu" style ="background-color: #7e70f0;">
    <div class="container">
    <a class="navbar-brand" href="#">POEM DAILY</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">Poemas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $login_url; ?>">Cerrar Sesión</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container" id="poemas">
    <!-- Aquí se mostrarán los poemas -->
    <h2 class="mb-4">MIS POEMASI</h2>

    <div class="dashboard-button-container">
        <button class="btn btn-primary" type="submit"><i class=""></i> Me gusta </button>
        <button class="btn btn-primary" type="submit"><i class=""></i> Favoritos </button>
    </div>
</div>

<!-- Bootstrap JS y dependencias (jQuery y Popper.js) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>
